fix(FEC-13987): Player v7 | Skip | Skip timeout (Hide skip control) configuration doesn't work, it applies the relative time that was configured for the intro\outro.
kaltura/playkit-js-skip pull request #24
Opened 2024-07-04 14:33 UTC by JonathanTGold

### Description of the Changes

Resolves FEC-13987

2024-07-05 10:57 UTC, semarche-kaltura requested changes

2024-07-05 10:57 UTC, semarche-kaltura commented on src/skip.js
> +      area: 'InteractiveArea',
```
KalturaPlayer.ui.ReservedPresetAreas.InteractiveArea;
```
or
```
import {ui} from '@playkit-js/kaltura-player-js';
const { InteractiveArea } = ui.ReservedPresetAreas;
```

2024-07-07 11:34 UTC, JonathanTGold commented on src/skip.js
> +      area: 'InteractiveArea',
fixed

2024-07-09 08:05 UTC, MosheMaorKaltura approved these changes

2024-07-09 10:47 UTC, SivanA-Kaltura approved these changes

2024-07-09 11:03 UTC, lianbenjamin approved these changes

2024-07-09 11:12 UTC, merged